@startuml

autonumber

== Initialization ==

Spring -> ConfigurationProcessor: Load configuration
ConfigurationProcessor -> DataIngestor: Ingest data
DataIngestor -> ConfigurationProcessor: data ingested
ConfigurationProcessor -> Spring: process other configurations

@enduml