app:
  oscars:
    csv-path: classpath:datasource/oscars.csv

spring:
  application:
    version: 0.0.1-SNAPSHOT
    name: oscars-ai-rag
    title: OscarsRagtime
  banner:
    location: banner.txt
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      redis:
        uri: redis://localhost:6379
        index: oscars-index
        prefix: "oscars:"
        initialize-schema: true
    observations:
      include-prompt: true     # careful with sensitive data
      include-completion: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 10002

logging:
  level:
    org.springframework.ai: info
    org.springframework.ai.chat.client.advisor: debug
    web: debug